"""create shifts table

Revision ID: 4fa90e560028
Revises: 69a665706138
Create Date: 2025-12-10 12:51:29.113087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fa90e560028'
down_revision: Union[str, None] = '69a665706138'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inspect_points_code', table_name='inspect_points')
    op.drop_index('ix_inspect_points_company_id', table_name='inspect_points')
    op.drop_index('ix_inspect_points_id', table_name='inspect_points')
    op.drop_index('ix_inspect_points_site_id', table_name='inspect_points')
    op.drop_table('inspect_points')
    op.alter_column('attendance', 'is_overtime',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('attendance', 'is_backup',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('checklist_items', 'mock_location',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index(op.f('ix_checklist_items_kpi_key'), 'checklist_items', ['kpi_key'], unique=False)
    op.alter_column('checklist_template_items', 'photo_required',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_checklist_template_items_kpi_key'), 'checklist_template_items', ['kpi_key'], unique=False)
    op.add_column('checklist_templates', sa.Column('division', sa.String(length=32), nullable=False))
    op.create_index(op.f('ix_checklist_templates_division'), 'checklist_templates', ['division'], unique=False)
    op.alter_column('checklists', 'division',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               nullable=False)
    op.create_index(op.f('ix_checklists_context_id'), 'checklists', ['context_id'], unique=False)
    op.create_index(op.f('ix_checklists_context_type'), 'checklists', ['context_type'], unique=False)
    op.create_index(op.f('ix_checklists_division'), 'checklists', ['division'], unique=False)
    op.add_column('cleaning_zones', sa.Column('division', sa.String(length=32), nullable=False))
    op.create_index(op.f('ix_cleaning_zones_division'), 'cleaning_zones', ['division'], unique=False)
    op.alter_column('security_reports', 'division',
               existing_type=sa.VARCHAR(length=32),
               nullable=False,
               existing_server_default=sa.text('("SECURITY")'))
    op.create_index(op.f('ix_security_reports_checklist_id'), 'security_reports', ['checklist_id'], unique=False)
    op.create_index(op.f('ix_security_reports_division'), 'security_reports', ['division'], unique=False)
    op.create_index(op.f('ix_security_reports_trip_id'), 'security_reports', ['trip_id'], unique=False)
    op.create_index(op.f('ix_security_reports_vehicle_id'), 'security_reports', ['vehicle_id'], unique=False)
    op.create_index(op.f('ix_security_reports_zone_id'), 'security_reports', ['zone_id'], unique=False)
    op.alter_column('sites', 'lat',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('sites', 'lng',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('sites', 'geofence_radius_m',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(100.0)'))
    op.create_index(op.f('ix_sites_qr_code'), 'sites', ['qr_code'], unique=True)
    op.alter_column('users', 'division',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_scope_id'), 'users', ['scope_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_scope_id'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.alter_column('users', 'division',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_sites_qr_code'), table_name='sites')
    op.alter_column('sites', 'geofence_radius_m',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(100.0)'))
    op.alter_column('sites', 'lng',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('sites', 'lat',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_index(op.f('ix_security_reports_zone_id'), table_name='security_reports')
    op.drop_index(op.f('ix_security_reports_vehicle_id'), table_name='security_reports')
    op.drop_index(op.f('ix_security_reports_trip_id'), table_name='security_reports')
    op.drop_index(op.f('ix_security_reports_division'), table_name='security_reports')
    op.drop_index(op.f('ix_security_reports_checklist_id'), table_name='security_reports')
    op.alter_column('security_reports', 'division',
               existing_type=sa.VARCHAR(length=32),
               nullable=True,
               existing_server_default=sa.text('("SECURITY")'))
    op.drop_index(op.f('ix_cleaning_zones_division'), table_name='cleaning_zones')
    op.drop_column('cleaning_zones', 'division')
    op.drop_index(op.f('ix_checklists_division'), table_name='checklists')
    op.drop_index(op.f('ix_checklists_context_type'), table_name='checklists')
    op.drop_index(op.f('ix_checklists_context_id'), table_name='checklists')
    op.alter_column('checklists', 'division',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_checklist_templates_division'), table_name='checklist_templates')
    op.drop_column('checklist_templates', 'division')
    op.drop_index(op.f('ix_checklist_template_items_kpi_key'), table_name='checklist_template_items')
    op.alter_column('checklist_template_items', 'photo_required',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_checklist_items_kpi_key'), table_name='checklist_items')
    op.alter_column('checklist_items', 'mock_location',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('attendance', 'is_backup',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('attendance', 'is_overtime',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_table('inspect_points',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('company_id', sa.INTEGER(), nullable=False),
    sa.Column('site_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('code', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inspect_points_site_id', 'inspect_points', ['site_id'], unique=False)
    op.create_index('ix_inspect_points_id', 'inspect_points', ['id'], unique=False)
    op.create_index('ix_inspect_points_company_id', 'inspect_points', ['company_id'], unique=False)
    op.create_index('ix_inspect_points_code', 'inspect_points', ['code'], unique=False)
    # ### end Alembic commands ###
