"""initial

Revision ID: 69a665706138
Revises: 
Create Date: 2025-12-09 10:36:58.561455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69a665706138'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_code'), 'companies', ['code'], unique=True)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_table('security_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('check_in_time', sa.DateTime(), nullable=True),
    sa.Column('check_out_time', sa.DateTime(), nullable=True),
    sa.Column('check_in_location', sa.String(length=255), nullable=True),
    sa.Column('check_out_location', sa.String(length=255), nullable=True),
    sa.Column('check_in_photo_path', sa.String(length=512), nullable=True),
    sa.Column('check_out_photo_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_attendance_company_id'), 'security_attendance', ['company_id'], unique=False)
    op.create_index(op.f('ix_security_attendance_id'), 'security_attendance', ['id'], unique=False)
    op.create_index(op.f('ix_security_attendance_site_id'), 'security_attendance', ['site_id'], unique=False)
    op.create_index(op.f('ix_security_attendance_user_id'), 'security_attendance', ['user_id'], unique=False)
    op.create_table('security_patrol_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('area_text', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('main_photo_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_patrol_logs_company_id'), 'security_patrol_logs', ['company_id'], unique=False)
    op.create_index(op.f('ix_security_patrol_logs_id'), 'security_patrol_logs', ['id'], unique=False)
    op.create_index(op.f('ix_security_patrol_logs_site_id'), 'security_patrol_logs', ['site_id'], unique=False)
    op.create_index(op.f('ix_security_patrol_logs_user_id'), 'security_patrol_logs', ['user_id'], unique=False)
    op.create_table('security_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('division', sa.String(length=32), nullable=False),
    sa.Column('report_type', sa.String(length=32), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('location_text', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('evidence_paths', sa.Text(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('checklist_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_reports_checklist_id'), 'security_reports', ['checklist_id'], unique=False)
    op.create_index(op.f('ix_security_reports_company_id'), 'security_reports', ['company_id'], unique=False)
    op.create_index(op.f('ix_security_reports_division'), 'security_reports', ['division'], unique=False)
    op.create_index(op.f('ix_security_reports_id'), 'security_reports', ['id'], unique=False)
    op.create_index(op.f('ix_security_reports_site_id'), 'security_reports', ['site_id'], unique=False)
    op.create_index(op.f('ix_security_reports_trip_id'), 'security_reports', ['trip_id'], unique=False)
    op.create_index(op.f('ix_security_reports_user_id'), 'security_reports', ['user_id'], unique=False)
    op.create_index(op.f('ix_security_reports_vehicle_id'), 'security_reports', ['vehicle_id'], unique=False)
    op.create_index(op.f('ix_security_reports_zone_id'), 'security_reports', ['zone_id'], unique=False)
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('geofence_radius_m', sa.Float(), nullable=True),
    sa.Column('qr_code', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_company_id'), 'sites', ['company_id'], unique=False)
    op.create_index(op.f('ix_sites_id'), 'sites', ['id'], unique=False)
    op.create_index(op.f('ix_sites_name'), 'sites', ['name'], unique=False)
    op.create_index(op.f('ix_sites_qr_code'), 'sites', ['qr_code'], unique=True)
    op.create_table('checklist_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('division', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('shift_type', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_templates_company_id'), 'checklist_templates', ['company_id'], unique=False)
    op.create_index(op.f('ix_checklist_templates_division'), 'checklist_templates', ['division'], unique=False)
    op.create_index(op.f('ix_checklist_templates_id'), 'checklist_templates', ['id'], unique=False)
    op.create_table('cleaning_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('division', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('qr_code', sa.String(length=256), nullable=True),
    sa.Column('floor', sa.String(length=64), nullable=True),
    sa.Column('area_type', sa.String(length=64), nullable=True),
    sa.Column('geofence_id', sa.Integer(), nullable=True),
    sa.Column('geofence_latitude', sa.String(length=32), nullable=True),
    sa.Column('geofence_longitude', sa.String(length=32), nullable=True),
    sa.Column('geofence_radius_meters', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cleaning_zones_company_id'), 'cleaning_zones', ['company_id'], unique=False)
    op.create_index(op.f('ix_cleaning_zones_division'), 'cleaning_zones', ['division'], unique=False)
    op.create_index(op.f('ix_cleaning_zones_id'), 'cleaning_zones', ['id'], unique=False)
    op.create_index(op.f('ix_cleaning_zones_qr_code'), 'cleaning_zones', ['qr_code'], unique=True)
    op.create_index(op.f('ix_cleaning_zones_site_id'), 'cleaning_zones', ['site_id'], unique=False)
    op.create_table('patrol_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patrol_routes_company_id'), 'patrol_routes', ['company_id'], unique=False)
    op.create_index(op.f('ix_patrol_routes_id'), 'patrol_routes', ['id'], unique=False)
    op.create_index(op.f('ix_patrol_routes_site_id'), 'patrol_routes', ['site_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('division', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('scope_type', sa.String(length=32), nullable=True),
    sa.Column('scope_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_scope_id'), 'users', ['scope_id'], unique=False)
    op.create_index(op.f('ix_users_site_id'), 'users', ['site_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('plate_number', sa.String(length=32), nullable=False),
    sa.Column('vehicle_type', sa.Enum('CAR', 'TRUCK', 'BUS', 'VAN', 'MOTORCYCLE', name='vehicletype'), nullable=False),
    sa.Column('make', sa.String(length=128), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'OUT_OF_SERVICE', 'IN_MAINTENANCE', 'SOLD', name='vehiclestatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_company_id'), 'vehicles', ['company_id'], unique=False)
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_vehicles_plate_number'), 'vehicles', ['plate_number'], unique=True)
    op.create_index(op.f('ix_vehicles_site_id'), 'vehicles', ['site_id'], unique=False)
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='announcementpriority'), nullable=False),
    sa.Column('scope', sa.Enum('ALL', 'DIVISIONS', 'USERS', name='announcementscope'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('require_ack', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcements_company_id'), 'announcements', ['company_id'], unique=False)
    op.create_index(op.f('ix_announcements_id'), 'announcements', ['id'], unique=False)
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('role_type', sa.String(length=32), nullable=False),
    sa.Column('checkin_time', sa.DateTime(), nullable=False),
    sa.Column('checkin_lat', sa.Float(), nullable=True),
    sa.Column('checkin_lng', sa.Float(), nullable=True),
    sa.Column('checkin_photo_path', sa.String(length=512), nullable=True),
    sa.Column('checkin_accuracy', sa.Float(), nullable=True),
    sa.Column('checkin_mock_location', sa.Boolean(), nullable=False),
    sa.Column('checkout_time', sa.DateTime(), nullable=True),
    sa.Column('checkout_lat', sa.Float(), nullable=True),
    sa.Column('checkout_lng', sa.Float(), nullable=True),
    sa.Column('checkout_photo_path', sa.String(length=512), nullable=True),
    sa.Column('checkout_accuracy', sa.Float(), nullable=True),
    sa.Column('checkout_mock_location', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', name='attendancestatus'), nullable=False),
    sa.Column('is_valid_location', sa.Boolean(), nullable=False),
    sa.Column('shift', sa.String(length=32), nullable=True),
    sa.Column('is_overtime', sa.Boolean(), nullable=False),
    sa.Column('is_backup', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_company_id'), 'attendance', ['company_id'], unique=False)
    op.create_index(op.f('ix_attendance_id'), 'attendance', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_role_type'), 'attendance', ['role_type'], unique=False)
    op.create_index(op.f('ix_attendance_site_id'), 'attendance', ['site_id'], unique=False)
    op.create_index(op.f('ix_attendance_user_id'), 'attendance', ['user_id'], unique=False)
    op.create_table('checklist_template_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('evidence_type', sa.String(length=32), nullable=False),
    sa.Column('auto_complete_rule', sa.JSON(), nullable=True),
    sa.Column('kpi_key', sa.String(length=64), nullable=True),
    sa.Column('answer_type', sa.String(length=16), nullable=True),
    sa.Column('photo_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['checklist_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_template_items_id'), 'checklist_template_items', ['id'], unique=False)
    op.create_index(op.f('ix_checklist_template_items_kpi_key'), 'checklist_template_items', ['kpi_key'], unique=False)
    op.create_index(op.f('ix_checklist_template_items_template_id'), 'checklist_template_items', ['template_id'], unique=False)
    op.create_table('checklists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('attendance_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('division', sa.String(length=32), nullable=False),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('shift_type', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'COMPLETED', 'INCOMPLETE', name='checkliststatus'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('context_type', sa.String(length=32), nullable=True),
    sa.Column('context_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attendance_id'], ['security_attendance.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['checklist_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklists_attendance_id'), 'checklists', ['attendance_id'], unique=False)
    op.create_index(op.f('ix_checklists_company_id'), 'checklists', ['company_id'], unique=False)
    op.create_index(op.f('ix_checklists_context_id'), 'checklists', ['context_id'], unique=False)
    op.create_index(op.f('ix_checklists_context_type'), 'checklists', ['context_type'], unique=False)
    op.create_index(op.f('ix_checklists_division'), 'checklists', ['division'], unique=False)
    op.create_index(op.f('ix_checklists_id'), 'checklists', ['id'], unique=False)
    op.create_index(op.f('ix_checklists_shift_date'), 'checklists', ['shift_date'], unique=False)
    op.create_index(op.f('ix_checklists_site_id'), 'checklists', ['site_id'], unique=False)
    op.create_index(op.f('ix_checklists_template_id'), 'checklists', ['template_id'], unique=False)
    op.create_index(op.f('ix_checklists_user_id'), 'checklists', ['user_id'], unique=False)
    op.create_table('cleaning_inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('inspector_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('photo_paths', sa.Text(), nullable=True),
    sa.Column('inspection_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['cleaning_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cleaning_inspections_company_id'), 'cleaning_inspections', ['company_id'], unique=False)
    op.create_index(op.f('ix_cleaning_inspections_id'), 'cleaning_inspections', ['id'], unique=False)
    op.create_index(op.f('ix_cleaning_inspections_inspector_id'), 'cleaning_inspections', ['inspector_id'], unique=False)
    op.create_index(op.f('ix_cleaning_inspections_site_id'), 'cleaning_inspections', ['site_id'], unique=False)
    op.create_index(op.f('ix_cleaning_inspections_zone_id'), 'cleaning_inspections', ['zone_id'], unique=False)
    op.create_table('cleaning_zone_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('checklist_template_id', sa.Integer(), nullable=False),
    sa.Column('frequency_type', sa.String(length=32), nullable=False),
    sa.Column('frequency_detail', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['checklist_template_id'], ['checklist_templates.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['cleaning_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cleaning_zone_templates_checklist_template_id'), 'cleaning_zone_templates', ['checklist_template_id'], unique=False)
    op.create_index(op.f('ix_cleaning_zone_templates_id'), 'cleaning_zone_templates', ['id'], unique=False)
    op.create_index(op.f('ix_cleaning_zone_templates_zone_id'), 'cleaning_zone_templates', ['zone_id'], unique=False)
    op.create_table('daily_activity_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('shift_type', sa.String(length=32), nullable=True),
    sa.Column('report_number', sa.String(length=32), nullable=False),
    sa.Column('generated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('summary_data', sa.JSON(), nullable=True),
    sa.Column('pdf_path', sa.String(length=512), nullable=True),
    sa.Column('html_path', sa.String(length=512), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['generated_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_activity_reports_company_id'), 'daily_activity_reports', ['company_id'], unique=False)
    op.create_index(op.f('ix_daily_activity_reports_id'), 'daily_activity_reports', ['id'], unique=False)
    op.create_index(op.f('ix_daily_activity_reports_report_number'), 'daily_activity_reports', ['report_number'], unique=True)
    op.create_index(op.f('ix_daily_activity_reports_shift_date'), 'daily_activity_reports', ['shift_date'], unique=False)
    op.create_index(op.f('ix_daily_activity_reports_site_id'), 'daily_activity_reports', ['site_id'], unique=False)
    op.create_table('dispatch_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('ticket_number', sa.String(length=32), nullable=False),
    sa.Column('caller_name', sa.String(length=255), nullable=True),
    sa.Column('caller_phone', sa.String(length=32), nullable=True),
    sa.Column('incident_type', sa.String(length=64), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.String(length=32), nullable=True),
    sa.Column('longitude', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'ASSIGNED', 'ONSCENE', 'CLOSED', 'CANCELLED', name='dispatchstatus'), nullable=False),
    sa.Column('assigned_to_user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('onscene_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('closed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['closed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatch_tickets_assigned_to_user_id'), 'dispatch_tickets', ['assigned_to_user_id'], unique=False)
    op.create_index(op.f('ix_dispatch_tickets_company_id'), 'dispatch_tickets', ['company_id'], unique=False)
    op.create_index(op.f('ix_dispatch_tickets_id'), 'dispatch_tickets', ['id'], unique=False)
    op.create_index(op.f('ix_dispatch_tickets_site_id'), 'dispatch_tickets', ['site_id'], unique=False)
    op.create_index(op.f('ix_dispatch_tickets_ticket_number'), 'dispatch_tickets', ['ticket_number'], unique=True)
    op.create_table('driver_trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('trip_date', sa.Date(), nullable=False),
    sa.Column('planned_start_time', sa.Time(), nullable=True),
    sa.Column('planned_end_time', sa.Time(), nullable=True),
    sa.Column('actual_start_time', sa.DateTime(), nullable=True),
    sa.Column('actual_end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='tripstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_trips_company_id'), 'driver_trips', ['company_id'], unique=False)
    op.create_index(op.f('ix_driver_trips_driver_id'), 'driver_trips', ['driver_id'], unique=False)
    op.create_index(op.f('ix_driver_trips_id'), 'driver_trips', ['id'], unique=False)
    op.create_index(op.f('ix_driver_trips_site_id'), 'driver_trips', ['site_id'], unique=False)
    op.create_index(op.f('ix_driver_trips_trip_date'), 'driver_trips', ['trip_date'], unique=False)
    op.create_index(op.f('ix_driver_trips_vehicle_id'), 'driver_trips', ['vehicle_id'], unique=False)
    op.create_table('guard_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.String(length=32), nullable=False),
    sa.Column('longitude', sa.String(length=32), nullable=False),
    sa.Column('accuracy', sa.String(length=16), nullable=True),
    sa.Column('heading', sa.String(length=16), nullable=True),
    sa.Column('speed', sa.String(length=16), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guard_locations_company_id'), 'guard_locations', ['company_id'], unique=False)
    op.create_index(op.f('ix_guard_locations_id'), 'guard_locations', ['id'], unique=False)
    op.create_index(op.f('ix_guard_locations_site_id'), 'guard_locations', ['site_id'], unique=False)
    op.create_index(op.f('ix_guard_locations_timestamp'), 'guard_locations', ['timestamp'], unique=False)
    op.create_index(op.f('ix_guard_locations_user_id'), 'guard_locations', ['user_id'], unique=False)
    op.create_table('idle_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=32), nullable=False),
    sa.Column('idle_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('last_activity_time', sa.DateTime(), nullable=True),
    sa.Column('latitude', sa.String(length=32), nullable=True),
    sa.Column('longitude', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('acknowledged_by_user_id', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idle_alerts_company_id'), 'idle_alerts', ['company_id'], unique=False)
    op.create_index(op.f('ix_idle_alerts_id'), 'idle_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_idle_alerts_site_id'), 'idle_alerts', ['site_id'], unique=False)
    op.create_index(op.f('ix_idle_alerts_user_id'), 'idle_alerts', ['user_id'], unique=False)
    op.create_table('panic_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=32), nullable=False),
    sa.Column('latitude', sa.String(length=32), nullable=False),
    sa.Column('longitude', sa.String(length=32), nullable=False),
    sa.Column('location_text', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('acknowledged_by_user_id', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_panic_alerts_company_id'), 'panic_alerts', ['company_id'], unique=False)
    op.create_index(op.f('ix_panic_alerts_id'), 'panic_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_panic_alerts_site_id'), 'panic_alerts', ['site_id'], unique=False)
    op.create_index(op.f('ix_panic_alerts_user_id'), 'panic_alerts', ['user_id'], unique=False)
    op.create_table('patrol_checkpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.String(length=32), nullable=True),
    sa.Column('longitude', sa.String(length=32), nullable=True),
    sa.Column('nfc_code', sa.String(length=128), nullable=True),
    sa.Column('qr_code', sa.String(length=128), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('time_window_start', sa.String(length=8), nullable=True),
    sa.Column('time_window_end', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['patrol_routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patrol_checkpoints_id'), 'patrol_checkpoints', ['id'], unique=False)
    op.create_index(op.f('ix_patrol_checkpoints_nfc_code'), 'patrol_checkpoints', ['nfc_code'], unique=True)
    op.create_index(op.f('ix_patrol_checkpoints_qr_code'), 'patrol_checkpoints', ['qr_code'], unique=True)
    op.create_index(op.f('ix_patrol_checkpoints_route_id'), 'patrol_checkpoints', ['route_id'], unique=False)
    op.create_table('post_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('expires_date', sa.Date(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_orders_company_id'), 'post_orders', ['company_id'], unique=False)
    op.create_index(op.f('ix_post_orders_id'), 'post_orders', ['id'], unique=False)
    op.create_index(op.f('ix_post_orders_site_id'), 'post_orders', ['site_id'], unique=False)
    op.create_table('shift_handovers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('from_shift_type', sa.String(length=32), nullable=True),
    sa.Column('to_shift_type', sa.String(length=32), nullable=True),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('acknowledged_by_user_id', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_handovers_company_id'), 'shift_handovers', ['company_id'], unique=False)
    op.create_index(op.f('ix_shift_handovers_id'), 'shift_handovers', ['id'], unique=False)
    op.create_index(op.f('ix_shift_handovers_shift_date'), 'shift_handovers', ['shift_date'], unique=False)
    op.create_index(op.f('ix_shift_handovers_site_id'), 'shift_handovers', ['site_id'], unique=False)
    op.create_table('shift_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('shift_type', sa.String(length=32), nullable=False),
    sa.Column('start_time', sa.String(length=8), nullable=True),
    sa.Column('end_time', sa.String(length=8), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_schedules_company_id'), 'shift_schedules', ['company_id'], unique=False)
    op.create_index(op.f('ix_shift_schedules_id'), 'shift_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_shift_schedules_shift_date'), 'shift_schedules', ['shift_date'], unique=False)
    op.create_index(op.f('ix_shift_schedules_site_id'), 'shift_schedules', ['site_id'], unique=False)
    op.create_index(op.f('ix_shift_schedules_user_id'), 'shift_schedules', ['user_id'], unique=False)
    op.create_table('announcement_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('announcement_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('is_ack', sa.Boolean(), nullable=False),
    sa.Column('ack_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcement_targets_announcement_id'), 'announcement_targets', ['announcement_id'], unique=False)
    op.create_index(op.f('ix_announcement_targets_id'), 'announcement_targets', ['id'], unique=False)
    op.create_index(op.f('ix_announcement_targets_user_id'), 'announcement_targets', ['user_id'], unique=False)
    op.create_table('checklist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checklist_id', sa.Integer(), nullable=False),
    sa.Column('template_item_id', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('evidence_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'NOT_APPLICABLE', 'FAILED', name='checklistitemstatus'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('evidence_id', sa.String(length=512), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('kpi_key', sa.String(length=64), nullable=True),
    sa.Column('answer_type', sa.String(length=16), nullable=True),
    sa.Column('answer_bool', sa.Boolean(), nullable=True),
    sa.Column('answer_int', sa.Integer(), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('photo_id', sa.Integer(), nullable=True),
    sa.Column('gps_lat', sa.Float(), nullable=True),
    sa.Column('gps_lng', sa.Float(), nullable=True),
    sa.Column('gps_accuracy', sa.Float(), nullable=True),
    sa.Column('mock_location', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.id'], ),
    sa.ForeignKeyConstraint(['template_item_id'], ['checklist_template_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_items_checklist_id'), 'checklist_items', ['checklist_id'], unique=False)
    op.create_index(op.f('ix_checklist_items_id'), 'checklist_items', ['id'], unique=False)
    op.create_index(op.f('ix_checklist_items_kpi_key'), 'checklist_items', ['kpi_key'], unique=False)
    op.create_index(op.f('ix_checklist_items_template_item_id'), 'checklist_items', ['template_item_id'], unique=False)
    op.create_table('driver_trip_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.String(length=32), nullable=True),
    sa.Column('longitude', sa.String(length=32), nullable=True),
    sa.Column('planned_arrival_time', sa.Time(), nullable=True),
    sa.Column('planned_departure_time', sa.Time(), nullable=True),
    sa.Column('actual_arrival_time', sa.DateTime(), nullable=True),
    sa.Column('actual_departure_time', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['driver_trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_trip_stops_id'), 'driver_trip_stops', ['id'], unique=False)
    op.create_index(op.f('ix_driver_trip_stops_trip_id'), 'driver_trip_stops', ['trip_id'], unique=False)
    op.create_table('patrol_checkpoint_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('checkpoint_id', sa.Integer(), nullable=False),
    sa.Column('scan_time', sa.DateTime(), nullable=False),
    sa.Column('scan_method', sa.String(length=16), nullable=False),
    sa.Column('scan_code', sa.String(length=128), nullable=True),
    sa.Column('latitude', sa.String(length=32), nullable=True),
    sa.Column('longitude', sa.String(length=32), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('is_missed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['checkpoint_id'], ['patrol_checkpoints.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['patrol_routes.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patrol_checkpoint_scans_checkpoint_id'), 'patrol_checkpoint_scans', ['checkpoint_id'], unique=False)
    op.create_index(op.f('ix_patrol_checkpoint_scans_company_id'), 'patrol_checkpoint_scans', ['company_id'], unique=False)
    op.create_index(op.f('ix_patrol_checkpoint_scans_id'), 'patrol_checkpoint_scans', ['id'], unique=False)
    op.create_index(op.f('ix_patrol_checkpoint_scans_route_id'), 'patrol_checkpoint_scans', ['route_id'], unique=False)
    op.create_index(op.f('ix_patrol_checkpoint_scans_scan_time'), 'patrol_checkpoint_scans', ['scan_time'], unique=False)
    op.create_index(op.f('ix_patrol_checkpoint_scans_site_id'), 'patrol_checkpoint_scans', ['site_id'], unique=False)
    op.create_index(op.f('ix_patrol_checkpoint_scans_user_id'), 'patrol_checkpoint_scans', ['user_id'], unique=False)
    op.create_table('post_order_acknowledgments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_order_id'], ['post_orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_order_acknowledgments_id'), 'post_order_acknowledgments', ['id'], unique=False)
    op.create_index(op.f('ix_post_order_acknowledgments_post_order_id'), 'post_order_acknowledgments', ['post_order_id'], unique=False)
    op.create_index(op.f('ix_post_order_acknowledgments_user_id'), 'post_order_acknowledgments', ['user_id'], unique=False)
    op.create_table('shift_exchanges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=True),
    sa.Column('from_shift_id', sa.Integer(), nullable=False),
    sa.Column('to_shift_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('request_message', sa.Text(), nullable=True),
    sa.Column('response_message', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('approval_status', sa.String(length=32), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['from_shift_id'], ['shift_schedules.id'], ),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['to_shift_id'], ['shift_schedules.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_exchanges_approved_by_user_id'), 'shift_exchanges', ['approved_by_user_id'], unique=False)
    op.create_index(op.f('ix_shift_exchanges_company_id'), 'shift_exchanges', ['company_id'], unique=False)
    op.create_index(op.f('ix_shift_exchanges_from_shift_id'), 'shift_exchanges', ['from_shift_id'], unique=False)
    op.create_index(op.f('ix_shift_exchanges_from_user_id'), 'shift_exchanges', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_shift_exchanges_id'), 'shift_exchanges', ['id'], unique=False)
    op.create_index(op.f('ix_shift_exchanges_site_id'), 'shift_exchanges', ['site_id'], unique=False)
    op.create_index(op.f('ix_shift_exchanges_to_shift_id'), 'shift_exchanges', ['to_shift_id'], unique=False)
    op.create_index(op.f('ix_shift_exchanges_to_user_id'), 'shift_exchanges', ['to_user_id'], unique=False)
    op.create_table('driver_trip_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.Enum('START', 'STOP_ARRIVAL', 'STOP_DEPARTURE', 'BREAKDOWN', 'ACCIDENT', 'FUEL', 'NOTE', 'END', name='tripeventtype'), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('latitude', sa.String(length=32), nullable=True),
    sa.Column('longitude', sa.String(length=32), nullable=True),
    sa.Column('gps_log_id', sa.Integer(), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stop_id'], ['driver_trip_stops.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['driver_trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_trip_events_id'), 'driver_trip_events', ['id'], unique=False)
    op.create_index(op.f('ix_driver_trip_events_stop_id'), 'driver_trip_events', ['stop_id'], unique=False)
    op.create_index(op.f('ix_driver_trip_events_time'), 'driver_trip_events', ['time'], unique=False)
    op.create_index(op.f('ix_driver_trip_events_trip_id'), 'driver_trip_events', ['trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_driver_trip_events_trip_id'), table_name='driver_trip_events')
    op.drop_index(op.f('ix_driver_trip_events_time'), table_name='driver_trip_events')
    op.drop_index(op.f('ix_driver_trip_events_stop_id'), table_name='driver_trip_events')
    op.drop_index(op.f('ix_driver_trip_events_id'), table_name='driver_trip_events')
    op.drop_table('driver_trip_events')
    op.drop_index(op.f('ix_shift_exchanges_to_user_id'), table_name='shift_exchanges')
    op.drop_index(op.f('ix_shift_exchanges_to_shift_id'), table_name='shift_exchanges')
    op.drop_index(op.f('ix_shift_exchanges_site_id'), table_name='shift_exchanges')
    op.drop_index(op.f('ix_shift_exchanges_id'), table_name='shift_exchanges')
    op.drop_index(op.f('ix_shift_exchanges_from_user_id'), table_name='shift_exchanges')
    op.drop_index(op.f('ix_shift_exchanges_from_shift_id'), table_name='shift_exchanges')
    op.drop_index(op.f('ix_shift_exchanges_company_id'), table_name='shift_exchanges')
    op.drop_index(op.f('ix_shift_exchanges_approved_by_user_id'), table_name='shift_exchanges')
    op.drop_table('shift_exchanges')
    op.drop_index(op.f('ix_post_order_acknowledgments_user_id'), table_name='post_order_acknowledgments')
    op.drop_index(op.f('ix_post_order_acknowledgments_post_order_id'), table_name='post_order_acknowledgments')
    op.drop_index(op.f('ix_post_order_acknowledgments_id'), table_name='post_order_acknowledgments')
    op.drop_table('post_order_acknowledgments')
    op.drop_index(op.f('ix_patrol_checkpoint_scans_user_id'), table_name='patrol_checkpoint_scans')
    op.drop_index(op.f('ix_patrol_checkpoint_scans_site_id'), table_name='patrol_checkpoint_scans')
    op.drop_index(op.f('ix_patrol_checkpoint_scans_scan_time'), table_name='patrol_checkpoint_scans')
    op.drop_index(op.f('ix_patrol_checkpoint_scans_route_id'), table_name='patrol_checkpoint_scans')
    op.drop_index(op.f('ix_patrol_checkpoint_scans_id'), table_name='patrol_checkpoint_scans')
    op.drop_index(op.f('ix_patrol_checkpoint_scans_company_id'), table_name='patrol_checkpoint_scans')
    op.drop_index(op.f('ix_patrol_checkpoint_scans_checkpoint_id'), table_name='patrol_checkpoint_scans')
    op.drop_table('patrol_checkpoint_scans')
    op.drop_index(op.f('ix_driver_trip_stops_trip_id'), table_name='driver_trip_stops')
    op.drop_index(op.f('ix_driver_trip_stops_id'), table_name='driver_trip_stops')
    op.drop_table('driver_trip_stops')
    op.drop_index(op.f('ix_checklist_items_template_item_id'), table_name='checklist_items')
    op.drop_index(op.f('ix_checklist_items_kpi_key'), table_name='checklist_items')
    op.drop_index(op.f('ix_checklist_items_id'), table_name='checklist_items')
    op.drop_index(op.f('ix_checklist_items_checklist_id'), table_name='checklist_items')
    op.drop_table('checklist_items')
    op.drop_index(op.f('ix_announcement_targets_user_id'), table_name='announcement_targets')
    op.drop_index(op.f('ix_announcement_targets_id'), table_name='announcement_targets')
    op.drop_index(op.f('ix_announcement_targets_announcement_id'), table_name='announcement_targets')
    op.drop_table('announcement_targets')
    op.drop_index(op.f('ix_shift_schedules_user_id'), table_name='shift_schedules')
    op.drop_index(op.f('ix_shift_schedules_site_id'), table_name='shift_schedules')
    op.drop_index(op.f('ix_shift_schedules_shift_date'), table_name='shift_schedules')
    op.drop_index(op.f('ix_shift_schedules_id'), table_name='shift_schedules')
    op.drop_index(op.f('ix_shift_schedules_company_id'), table_name='shift_schedules')
    op.drop_table('shift_schedules')
    op.drop_index(op.f('ix_shift_handovers_site_id'), table_name='shift_handovers')
    op.drop_index(op.f('ix_shift_handovers_shift_date'), table_name='shift_handovers')
    op.drop_index(op.f('ix_shift_handovers_id'), table_name='shift_handovers')
    op.drop_index(op.f('ix_shift_handovers_company_id'), table_name='shift_handovers')
    op.drop_table('shift_handovers')
    op.drop_index(op.f('ix_post_orders_site_id'), table_name='post_orders')
    op.drop_index(op.f('ix_post_orders_id'), table_name='post_orders')
    op.drop_index(op.f('ix_post_orders_company_id'), table_name='post_orders')
    op.drop_table('post_orders')
    op.drop_index(op.f('ix_patrol_checkpoints_route_id'), table_name='patrol_checkpoints')
    op.drop_index(op.f('ix_patrol_checkpoints_qr_code'), table_name='patrol_checkpoints')
    op.drop_index(op.f('ix_patrol_checkpoints_nfc_code'), table_name='patrol_checkpoints')
    op.drop_index(op.f('ix_patrol_checkpoints_id'), table_name='patrol_checkpoints')
    op.drop_table('patrol_checkpoints')
    op.drop_index(op.f('ix_panic_alerts_user_id'), table_name='panic_alerts')
    op.drop_index(op.f('ix_panic_alerts_site_id'), table_name='panic_alerts')
    op.drop_index(op.f('ix_panic_alerts_id'), table_name='panic_alerts')
    op.drop_index(op.f('ix_panic_alerts_company_id'), table_name='panic_alerts')
    op.drop_table('panic_alerts')
    op.drop_index(op.f('ix_idle_alerts_user_id'), table_name='idle_alerts')
    op.drop_index(op.f('ix_idle_alerts_site_id'), table_name='idle_alerts')
    op.drop_index(op.f('ix_idle_alerts_id'), table_name='idle_alerts')
    op.drop_index(op.f('ix_idle_alerts_company_id'), table_name='idle_alerts')
    op.drop_table('idle_alerts')
    op.drop_index(op.f('ix_guard_locations_user_id'), table_name='guard_locations')
    op.drop_index(op.f('ix_guard_locations_timestamp'), table_name='guard_locations')
    op.drop_index(op.f('ix_guard_locations_site_id'), table_name='guard_locations')
    op.drop_index(op.f('ix_guard_locations_id'), table_name='guard_locations')
    op.drop_index(op.f('ix_guard_locations_company_id'), table_name='guard_locations')
    op.drop_table('guard_locations')
    op.drop_index(op.f('ix_driver_trips_vehicle_id'), table_name='driver_trips')
    op.drop_index(op.f('ix_driver_trips_trip_date'), table_name='driver_trips')
    op.drop_index(op.f('ix_driver_trips_site_id'), table_name='driver_trips')
    op.drop_index(op.f('ix_driver_trips_id'), table_name='driver_trips')
    op.drop_index(op.f('ix_driver_trips_driver_id'), table_name='driver_trips')
    op.drop_index(op.f('ix_driver_trips_company_id'), table_name='driver_trips')
    op.drop_table('driver_trips')
    op.drop_index(op.f('ix_dispatch_tickets_ticket_number'), table_name='dispatch_tickets')
    op.drop_index(op.f('ix_dispatch_tickets_site_id'), table_name='dispatch_tickets')
    op.drop_index(op.f('ix_dispatch_tickets_id'), table_name='dispatch_tickets')
    op.drop_index(op.f('ix_dispatch_tickets_company_id'), table_name='dispatch_tickets')
    op.drop_index(op.f('ix_dispatch_tickets_assigned_to_user_id'), table_name='dispatch_tickets')
    op.drop_table('dispatch_tickets')
    op.drop_index(op.f('ix_daily_activity_reports_site_id'), table_name='daily_activity_reports')
    op.drop_index(op.f('ix_daily_activity_reports_shift_date'), table_name='daily_activity_reports')
    op.drop_index(op.f('ix_daily_activity_reports_report_number'), table_name='daily_activity_reports')
    op.drop_index(op.f('ix_daily_activity_reports_id'), table_name='daily_activity_reports')
    op.drop_index(op.f('ix_daily_activity_reports_company_id'), table_name='daily_activity_reports')
    op.drop_table('daily_activity_reports')
    op.drop_index(op.f('ix_cleaning_zone_templates_zone_id'), table_name='cleaning_zone_templates')
    op.drop_index(op.f('ix_cleaning_zone_templates_id'), table_name='cleaning_zone_templates')
    op.drop_index(op.f('ix_cleaning_zone_templates_checklist_template_id'), table_name='cleaning_zone_templates')
    op.drop_table('cleaning_zone_templates')
    op.drop_index(op.f('ix_cleaning_inspections_zone_id'), table_name='cleaning_inspections')
    op.drop_index(op.f('ix_cleaning_inspections_site_id'), table_name='cleaning_inspections')
    op.drop_index(op.f('ix_cleaning_inspections_inspector_id'), table_name='cleaning_inspections')
    op.drop_index(op.f('ix_cleaning_inspections_id'), table_name='cleaning_inspections')
    op.drop_index(op.f('ix_cleaning_inspections_company_id'), table_name='cleaning_inspections')
    op.drop_table('cleaning_inspections')
    op.drop_index(op.f('ix_checklists_user_id'), table_name='checklists')
    op.drop_index(op.f('ix_checklists_template_id'), table_name='checklists')
    op.drop_index(op.f('ix_checklists_site_id'), table_name='checklists')
    op.drop_index(op.f('ix_checklists_shift_date'), table_name='checklists')
    op.drop_index(op.f('ix_checklists_id'), table_name='checklists')
    op.drop_index(op.f('ix_checklists_division'), table_name='checklists')
    op.drop_index(op.f('ix_checklists_context_type'), table_name='checklists')
    op.drop_index(op.f('ix_checklists_context_id'), table_name='checklists')
    op.drop_index(op.f('ix_checklists_company_id'), table_name='checklists')
    op.drop_index(op.f('ix_checklists_attendance_id'), table_name='checklists')
    op.drop_table('checklists')
    op.drop_index(op.f('ix_checklist_template_items_template_id'), table_name='checklist_template_items')
    op.drop_index(op.f('ix_checklist_template_items_kpi_key'), table_name='checklist_template_items')
    op.drop_index(op.f('ix_checklist_template_items_id'), table_name='checklist_template_items')
    op.drop_table('checklist_template_items')
    op.drop_index(op.f('ix_attendance_user_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_site_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_role_type'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_company_id'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_announcements_id'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_company_id'), table_name='announcements')
    op.drop_table('announcements')
    op.drop_index(op.f('ix_vehicles_site_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_plate_number'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_company_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_site_id'), table_name='users')
    op.drop_index(op.f('ix_users_scope_id'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_patrol_routes_site_id'), table_name='patrol_routes')
    op.drop_index(op.f('ix_patrol_routes_id'), table_name='patrol_routes')
    op.drop_index(op.f('ix_patrol_routes_company_id'), table_name='patrol_routes')
    op.drop_table('patrol_routes')
    op.drop_index(op.f('ix_cleaning_zones_site_id'), table_name='cleaning_zones')
    op.drop_index(op.f('ix_cleaning_zones_qr_code'), table_name='cleaning_zones')
    op.drop_index(op.f('ix_cleaning_zones_id'), table_name='cleaning_zones')
    op.drop_index(op.f('ix_cleaning_zones_division'), table_name='cleaning_zones')
    op.drop_index(op.f('ix_cleaning_zones_company_id'), table_name='cleaning_zones')
    op.drop_table('cleaning_zones')
    op.drop_index(op.f('ix_checklist_templates_id'), table_name='checklist_templates')
    op.drop_index(op.f('ix_checklist_templates_division'), table_name='checklist_templates')
    op.drop_index(op.f('ix_checklist_templates_company_id'), table_name='checklist_templates')
    op.drop_table('checklist_templates')
    op.drop_index(op.f('ix_sites_qr_code'), table_name='sites')
    op.drop_index(op.f('ix_sites_name'), table_name='sites')
    op.drop_index(op.f('ix_sites_id'), table_name='sites')
    op.drop_index(op.f('ix_sites_company_id'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_security_reports_zone_id'), table_name='security_reports')
    op.drop_index(op.f('ix_security_reports_vehicle_id'), table_name='security_reports')
    op.drop_index(op.f('ix_security_reports_user_id'), table_name='security_reports')
    op.drop_index(op.f('ix_security_reports_trip_id'), table_name='security_reports')
    op.drop_index(op.f('ix_security_reports_site_id'), table_name='security_reports')
    op.drop_index(op.f('ix_security_reports_id'), table_name='security_reports')
    op.drop_index(op.f('ix_security_reports_division'), table_name='security_reports')
    op.drop_index(op.f('ix_security_reports_company_id'), table_name='security_reports')
    op.drop_index(op.f('ix_security_reports_checklist_id'), table_name='security_reports')
    op.drop_table('security_reports')
    op.drop_index(op.f('ix_security_patrol_logs_user_id'), table_name='security_patrol_logs')
    op.drop_index(op.f('ix_security_patrol_logs_site_id'), table_name='security_patrol_logs')
    op.drop_index(op.f('ix_security_patrol_logs_id'), table_name='security_patrol_logs')
    op.drop_index(op.f('ix_security_patrol_logs_company_id'), table_name='security_patrol_logs')
    op.drop_table('security_patrol_logs')
    op.drop_index(op.f('ix_security_attendance_user_id'), table_name='security_attendance')
    op.drop_index(op.f('ix_security_attendance_site_id'), table_name='security_attendance')
    op.drop_index(op.f('ix_security_attendance_id'), table_name='security_attendance')
    op.drop_index(op.f('ix_security_attendance_company_id'), table_name='security_attendance')
    op.drop_table('security_attendance')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_code'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
