"""add missing models

Revision ID: 038e8b3bbc26
Revises: 0622a611d594
Create Date: 2025-12-10 15:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite


# revision identifiers, used by Alembic.
revision: str = '038e8b3bbc26'
down_revision: Union[str, None] = '0622a611d594'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create inspect_points table (was dropped in previous migration)
    op.create_table('inspect_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspect_points_id'), 'inspect_points', ['id'], unique=False)
    op.create_index(op.f('ix_inspect_points_company_id'), 'inspect_points', ['company_id'], unique=False)
    op.create_index(op.f('ix_inspect_points_site_id'), 'inspect_points', ['site_id'], unique=False)
    op.create_index(op.f('ix_inspect_points_code'), 'inspect_points', ['code'], unique=True)
    
    # Create attendance_corrections table
    op.create_table('attendance_corrections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('attendance_id', sa.Integer(), nullable=True),
    sa.Column('correction_type', sa.Enum('LATE', 'MISSING_CLOCK_IN', 'MISSING_CLOCK_OUT', 'OVERTIME', name='correctiontype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='correctionstatus'), nullable=False),
    sa.Column('requested_clock_in', sa.DateTime(), nullable=True),
    sa.Column('requested_clock_out', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence_url', sa.String(length=512), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('rejected_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendance.id'], ),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_corrections_id'), 'attendance_corrections', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_corrections_company_id'), 'attendance_corrections', ['company_id'], unique=False)
    op.create_index(op.f('ix_attendance_corrections_user_id'), 'attendance_corrections', ['user_id'], unique=False)
    op.create_index(op.f('ix_attendance_corrections_attendance_id'), 'attendance_corrections', ['attendance_id'], unique=False)
    
    # Create leave_requests table
    op.create_table('leave_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('request_type', sa.Enum('PERMISSION', 'LEAVE', 'SICK', 'OTHER', name='requesttype'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='requeststatus'), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_requests_id'), 'leave_requests', ['id'], unique=False)
    op.create_index(op.f('ix_leave_requests_user_id'), 'leave_requests', ['user_id'], unique=False)
    op.create_index(op.f('ix_leave_requests_company_id'), 'leave_requests', ['company_id'], unique=False)
    op.create_index(op.f('ix_leave_requests_site_id'), 'leave_requests', ['site_id'], unique=False)
    op.create_index(op.f('ix_leave_requests_request_type'), 'leave_requests', ['request_type'], unique=False)
    op.create_index(op.f('ix_leave_requests_start_date'), 'leave_requests', ['start_date'], unique=False)
    op.create_index(op.f('ix_leave_requests_status'), 'leave_requests', ['status'], unique=False)
    
    # Create devices table
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('device_model', sa.String(length=255), nullable=True),
    sa.Column('os_version', sa.String(length=64), nullable=True),
    sa.Column('app_version', sa.String(length=32), nullable=True),
    sa.Column('time_offset_sec', sa.Float(), nullable=False),
    sa.Column('time_trusted', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_index(op.f('ix_devices_device_id'), 'devices', ['device_id'], unique=True)
    op.create_index(op.f('ix_devices_user_id'), 'devices', ['user_id'], unique=False)
    op.create_index(op.f('ix_devices_company_id'), 'devices', ['company_id'], unique=False)
    
    # Create client_events table
    op.create_table('client_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('client_event_id', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('server_received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('mapped_entity_id', sa.Integer(), nullable=True),
    sa.Column('time_suspect', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_events_id'), 'client_events', ['id'], unique=False)
    op.create_index(op.f('ix_client_events_device_id'), 'client_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_client_events_client_event_id'), 'client_events', ['client_event_id'], unique=False)
    op.create_index(op.f('ix_client_events_type'), 'client_events', ['type'], unique=False)
    op.create_index(op.f('ix_client_events_event_time'), 'client_events', ['event_time'], unique=False)
    op.create_index(op.f('ix_client_events_mapped_entity_id'), 'client_events', ['mapped_entity_id'], unique=False)
    
    # Create shifts table
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('division', sa.String(length=32), nullable=False),
    sa.Column('shift_date', sa.DateTime(), nullable=False),
    sa.Column('start_time', sa.String(length=8), nullable=False),
    sa.Column('end_time', sa.String(length=8), nullable=False),
    sa.Column('shift_type', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ASSIGNED', 'OPEN', 'COMPLETED', 'CANCELLED', name='shiftstatus'), nullable=False),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shifts_id'), 'shifts', ['id'], unique=False)
    op.create_index(op.f('ix_shifts_company_id'), 'shifts', ['company_id'], unique=False)
    op.create_index(op.f('ix_shifts_site_id'), 'shifts', ['site_id'], unique=False)
    op.create_index(op.f('ix_shifts_division'), 'shifts', ['division'], unique=False)
    op.create_index(op.f('ix_shifts_shift_date'), 'shifts', ['shift_date'], unique=False)
    op.create_index(op.f('ix_shifts_user_id'), 'shifts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shifts_user_id'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_shift_date'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_division'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_site_id'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_company_id'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_id'), table_name='shifts')
    op.drop_table('shifts')
    op.drop_index(op.f('ix_client_events_mapped_entity_id'), table_name='client_events')
    op.drop_index(op.f('ix_client_events_event_time'), table_name='client_events')
    op.drop_index(op.f('ix_client_events_type'), table_name='client_events')
    op.drop_index(op.f('ix_client_events_client_event_id'), table_name='client_events')
    op.drop_index(op.f('ix_client_events_device_id'), table_name='client_events')
    op.drop_index(op.f('ix_client_events_id'), table_name='client_events')
    op.drop_table('client_events')
    op.drop_index(op.f('ix_devices_company_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_user_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_leave_requests_status'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_start_date'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_request_type'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_site_id'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_company_id'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_user_id'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_id'), table_name='leave_requests')
    op.drop_table('leave_requests')
    op.drop_index(op.f('ix_attendance_corrections_attendance_id'), table_name='attendance_corrections')
    op.drop_index(op.f('ix_attendance_corrections_user_id'), table_name='attendance_corrections')
    op.drop_index(op.f('ix_attendance_corrections_company_id'), table_name='attendance_corrections')
    op.drop_index(op.f('ix_attendance_corrections_id'), table_name='attendance_corrections')
    op.drop_table('attendance_corrections')
    op.drop_index(op.f('ix_inspect_points_code'), table_name='inspect_points')
    op.drop_index(op.f('ix_inspect_points_site_id'), table_name='inspect_points')
    op.drop_index(op.f('ix_inspect_points_company_id'), table_name='inspect_points')
    op.drop_index(op.f('ix_inspect_points_id'), table_name='inspect_points')
    op.drop_table('inspect_points')
    # ### end Alembic commands ###

