"""add_announcement_tables

Revision ID: d3ce722b389e
Revises: 001
Create Date: 2025-12-05 11:37:09.235383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3ce722b389e'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create announcement tables
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),  # SQLite doesn't support Enum, use String
    sa.Column('scope', sa.String(length=20), nullable=False),  # SQLite doesn't support Enum, use String
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('require_ack', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcements_company_id'), 'announcements', ['company_id'], unique=False)
    op.create_index(op.f('ix_announcements_id'), 'announcements', ['id'], unique=False)
    op.create_table('announcement_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('announcement_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('is_ack', sa.Boolean(), nullable=False),
    sa.Column('ack_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcement_targets_announcement_id'), 'announcement_targets', ['announcement_id'], unique=False)
    op.create_index(op.f('ix_announcement_targets_id'), 'announcement_targets', ['id'], unique=False)
    op.create_index(op.f('ix_announcement_targets_user_id'), 'announcement_targets', ['user_id'], unique=False)
    
    # Note: SQLite has limited ALTER TABLE support, so we skip other changes
    # The announcement tables are the main focus of this migration
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop announcement tables
    op.drop_index(op.f('ix_announcement_targets_user_id'), table_name='announcement_targets')
    op.drop_index(op.f('ix_announcement_targets_id'), table_name='announcement_targets')
    op.drop_index(op.f('ix_announcement_targets_announcement_id'), table_name='announcement_targets')
    op.drop_table('announcement_targets')
    op.drop_index(op.f('ix_announcements_id'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_company_id'), table_name='announcements')
    op.drop_table('announcements')
    # ### end Alembic commands ###
